### ISSUE TITLE
How to write to firestore after geofirestore query

### ISSUE THREAD

**Issue by k0302** [MichaelSolati/geofirestore-js#206] opened 2021-01-15 21:27 UTC
I have a question about writing to firestore from cloud functions after geofirestore query. 
I queried my firestore collection `users/userId/pros', and got documents `users/userId/pros/proId1' and `users/userId/pros/proId2' from the geofirestore query. 
Now, I want to add 'notif' collection to these documents - proId1, proId2. For that, I wrote code in cloud functions like this;

    const firestore = admin.firestore(); 
    const geofirestore = new GeoFirestore(firestore);             
    exports.sendNotification =                                           
    functions.firestore.document("users/{userId}/clients/{client}")    
    .onCreate(async snapshot => {  
    const clientfield = snapshot.data().field; 
    const clientgeopoint =  snapshot.data().g.geopoint; 
    const geocollection = geofirestore.collectionGroup('pros');   
    const query = geocollection.near({center: clientgeopoint, radius: 
    10}).where('field', '==',       clientfield); 
     await query.get().then( querySnapshot => { 
    querySnapshot.forEach(async doc    => { await 
    doc.ref.collection('notifs').add({ 'field': clientfield, ... 
    }); }); }).catch ((error) => console.log(error) ); })

 After executing this code, I get error on cloud functions console saying 'TypeError: Cannot read property 'collection' of undefined'. Please give me some tip on how to fix this code to make this work. Thanks.

**Comment by MichaelSolati** [comment] 2021-01-15 22:08
Duplicate of issue #192

**Closed by MichaelSolati** 2021-01-15 22:08 UTC
