### ISSUE TITLE
Support for new firestore 9.x? 

### ISSUE THREAD

**Issue by garyrylander** [MichaelSolati/geofirestore-js#224] opened 2021-12-20 18:09 UTC
### [REQUIRED] Describe your environment

- Operating System version: winows
- Browser version: Chrome
- Firebase library (`firebase`, `firebase-admin`, etc...) and version: _____
- GeoFirestore version: 4.4.2

### [REQUIRED] Describe the problem

Upgrading to Ionic V6 and Firebase V9.x

(Upgrade from version 8 to the modular Web SDK )

I am having issues just initializing 'geofirestore.initialApp(this.firestore)' 

this.firestore initialized at firestore = firebase.firestore();

Ionic 6 requires Angular ^13.0.0.

Any guidance here would be greatly appreciated. 

Gary Rylander
Garyrylander@gmail.com

**Comment by MichaelSolati** [comment] 2021-12-20 19:32
Duplicate of #219 

Though to answer the question I haven't had time. If you're using the `compat` you can just ignore the typing error, but as for supporting modular I'll hopefully look at it over the holidays.

**Closed by MichaelSolati** 2021-12-20 19:32 UTC
